#install only - add walltalk desktop configuration file to /home/pi/.config/autostart.  This calls walltalk.sh.

all:

install:
	mkdir -p /home/pi/.config/autostart
	cp -p -f walltalk.desktop /home/pi/.config/autostart